# Generated by Django 4.0.4 on 2022-06-04 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='memes/'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(default='Memino', max_length=30),
        ),
        migrations.AlterField(
            model_name='meme',
            name='title_html',
            field=models.CharField(default='Memino', editable=False, max_length=30),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meme.meme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
