# Generated by Django 4.0.4 on 2022-06-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0004_meme_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='likes',
        ),
    ]
