# Generated by Django 4.0.5 on 2022-07-03 15:42

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('meme', '0007_meme_dislikes_meme_likes_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
