# Generated by Django 4.0.5 on 2022-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0012_remove_meme_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
