# Generated by Django 4.0.6 on 2022-09-01 10:20

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('meme', '0015_meme_useroriginal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
